### ISSUE TITLE
Schema properties

### ISSUE THREAD

**Issue by blootsvoets** [NLeSC/software.esciencecenter.nl#14]
Describing the person properties now. Would it make sense to

1. Rename `person#/organization` to `person#/affiliation` and make it an array? This way the intention of the property is more clear to me (it is the name in JSON-LD as well), and we allow multiple affiliations (e.g. Wilco at NLeSC and Wageningen.)
2. Add `organization#/description` property, so organisations also have a text entry.
3. Rename `#/link/description` to `#/link/type`? It is only an enum to choose from, not really a description. In JSON-LD, instead they just prepend the link type. So instead of "link": [{"url": "http://github.com/estep/estep", "type": "repository"}] you'd get "repositoryUrl": "http://github.com/estep/estep"
4. `person#/photo` would be `person#/image` in JSON-LD.
5. Rename `software#/descriptionNonTech` to `software#/descriptionNonTechnical`? Writing out names is clearer.

**Comment by blootsvoets** [comment]
Mostly done (in branch schema_properties_issue_14). Waiting for Stefan to adjust data (md) files.

**Comment by sverhoeven** [comment]
See #19
