### ISSUE TITLE
Add supporter / endorsedBy relation

### ISSUE THREAD

**Issue by wrvhage** [NLeSC/software.esciencecenter.nl#145]
Add schema relation to denote who added the software to the eStep site and who wants to be involved in technical support in some way.

**Comment by wrvhage** [comment]
Having some issues with naming the "groups". If I use URIs to name the parties then I get URIs as values in the analytics page (e.g. http://software.esciencecenter.nl/organization/nlesc).
Still TODO: turn row chart into a menu at the top of the page.

**Comment by Maartenvm** [comment]
"Still TODO: turn row chart into a menu at the top of the page."

Don't know what you want exactly. Can you provide me with a mockup?

**Comment by Maartenvm** [comment]
Done in angular version.
