### ISSUE TITLE
add Lunr search to all of the website

### ISSUE THREAD

**Issue by wrvhage** [NLeSC/software.esciencecenter.nl#151]
If this does not scale, try pre-indexing. Otherwise, add new issue for server-side index.

**Comment by sverhoeven** [comment]
On my laptop it takes about 700ms in Chrome to fetch the index.json and create lunr indexes from it.

**Comment by sverhoeven** [comment]
If loading takes too long we could use Web workers (see http://renditionprotocol.blogspot.nl/2014/02/first-attempt-at-web-worker-for-lunarjs.html) to create lunr indices in the background.

**Comment by sverhoeven** [comment]
Or switch to http://elasticlunr.com/, they themselves say they are faster than lunr.js .

**Comment by Maartenvm** [comment]
We have now implemented this using regexp, for filtering. Lunr is not needed IMO.
