### ISSUE TITLE
schemas do not support relative paths

### ISSUE THREAD

**Issue by nielsdrost** [NLeSC/software.esciencecenter.nl#154]
Sometimes we refer to files/pages that are within the site. We would like to use a relative uri there. The schema validator does not support relative uri's.

**Comment by blootsvoets** [comment]
Note: JSON Schema does support relative URI's, see specification of `$ref` in https://spacetelescope.github.io/understanding-json-schema/structuring.html
There, URLs are resolved relatively to the document ID. We should do the same.

**Comment by blootsvoets** [comment]
Fixed in #165.
