### ISSUE TITLE
oxfrei dataset has invalid uri

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/software.esciencecenter.nl#205]
http://dx.doi.org/10.5281/zenodo.5156
not a uri
travis output: https://travis-ci.org/NLeSC/software.esciencecenter.nl/builds/177719747

**Comment by jspaaks** [comment]
correct links are (not sure why it's decrementing, maybe they were published out of order or something)
http://dx.doi.org/10.5281/zenodo.45156 (v0.1)
http://dx.doi.org/10.5281/zenodo.45155 (v1.0)

**Comment by jspaaks** [comment]
changed it to have it point to the latest (v1.0)

**Comment by elboyran** [comment]
Thanks. Not sure why was pointing wrongly.

**Comment by jspaaks** [comment]
resolved, merged, closing.
