### ISSUE TITLE
Make software list page the index page

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/software.esciencecenter.nl#22]
If you go to the software website via http://estep.esciencecenter.nl/ you would expect to see a list of software and not a blurp about eStep.

Rename software.html to index.html

**Comment by wrvhage** [comment]
No, if you go to http://software.esciencecenter.nl/ you would expect to see software.html, not a blurb about eStep. http://estep.esciencecenter.nl/ is ok.
