### ISSUE TITLE
Validate links

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/software.esciencecenter.nl#3]
The links the the markdown files should be validated as well.

eg. Jason is the owner of Xenon. The validator should check that the Jason person markdown file exists.

**Comment by blootsvoets** [comment]
Figured out why the current implementation does not show up as an error. The `$ref` is in an `anyOf` block, which means that as longs as one of the subblocks validate (it is still a valid URL), errors in other blocks will be ignored. We should probably test not the `$ref` but the URL. I'll take a look how.

**Comment by blootsvoets** [comment]
Fixed with PR #27.
