### ISSUE TITLE
Algorithmic optimalization / modeling

### ISSUE THREAD

**Issue by egpbos** [NLeSC/software.esciencecenter.nl#30]
For my new project, one main challenge is redesigning the algorithm in such a way that it can be parallelized (the way I understood it, the actual parallelization of the code should be a breeze after that is done, let's see ;) ). Should something like this be an expertise as well? I think it still qualifies as technical, but in a more theoretical / less directly applied way than other expertises.

**Comment by wrvhage** [comment]
The expertises are a management thing. These are the things we advertise ourselves with. There's lots of other things we're good at that we don't advertise. We could add them as technologyTag.
