### ISSUE TITLE
Fix dead internal links

### ISSUE THREAD

**Issue by blootsvoets** [NLeSC/software.esciencecenter.nl#33]
Right now we have 23 dead internal links. Those need some base information to resolve.

**Comment by blootsvoets** [comment]
@sverhoeven could you add an entry for `_person/e.tjongkimsang.md` to fix the `_software/twiqs.nl.md` file? I don't his/her details.

**Comment by blootsvoets** [comment]
Never mind. Fixed with #36 .

**Comment by sverhoeven** [comment]
@wrvhage  Erik made the Twiqs and worked on TwinNL project when he was engineer at NLeSC, should he not have his own person markdown file?

Lode still had his biography and photo so making a person markdown file is not that hard.

**Comment by wrvhage** [comment]
yes.

| New Call for Proposals 2016 | More information www.esciencecenter.nl/project-calls<applewebdata://F080E7EB-ADB6-4560-BE2B-42A2F19F4E41/www.eScienceCenter.nl/project-calls> |
| Funding opportunities for data-driven and compute-intensive research |

| Dr. Willem van Hage | Technology Lead Data Management and Analytics | email: w.vanhage@esciencecenter.nl<mailto:w.vanhage@esciencecenter.nl> |
| Netherlands eScience Center | Science Park 140 | 1098 XG Amsterdam | The Netherlands |
| The Netherlands eScience Center is a joint initiative by SURF and NWO | www.nlesc.nl<http://www.nlesc.nl/> |

On 06 Apr 2016, at 11:39, Stefan Verhoeven <notifications@github.com<mailto:notifications@github.com>> wrote:


@wrvhage<https://github.com/wrvhage> Erik made the Twiqs and worked on TwinNL project when he was engineer at NLeSC, should he not have his own person markdown file?

Lode still had his biography and photo so making a person markdown file is not that hard.

**Comment by blootsvoets** [comment]
@sverhoeven could you add his details then?
