### ISSUE TITLE
Link consistency check causes problems with incremental updates

### ISSUE THREAD

**Issue by egpbos** [NLeSC/software.esciencecenter.nl#40]
See https://github.com/NLeSC/software.esciencecenter.nl/pull/28#issuecomment-206395243. It may be better to turn off the checking of links again, for the time being, otherwise there will be chaos tomorrow, every time someone cross-links someone else's project/software/organization.

**Comment by egpbos** [comment]
Solution: removing links or creating stub personal files. This should be added to the README.

**Comment by blootsvoets** [comment]
People can create stubs or remove links for the time being. I'd prefer to keep in the checks, so people don't leave until they have everything filled in. @wrvhage agree?

**Comment by egpbos** [comment]
By the way, the checks didn't report any errors locally for me, only with Travis did they show up.

**Comment by blootsvoets** [comment]
They should, on the latest commits. pip reinstall?

**Comment by egpbos** [comment]
No fish. If I add `http://software.esciencecenter.nl/person/l.buitinck` as owner to xtas.md, validation goes just fine locally.

**Comment by blootsvoets** [comment]
updated readme

**Comment by wrvhage** [comment]
Stubs are ok, as long as we have a clear bold red warning somewhere that we still have to fill in the stub.

Willem

| New Call for Proposals 2016 | More information www.esciencecenter.nl/project-calls<applewebdata://F080E7EB-ADB6-4560-BE2B-42A2F19F4E41/www.eScienceCenter.nl/project-calls> |
| Funding opportunities for data-driven and compute-intensive research |

| Dr. Willem van Hage | Technology Lead Data Management and Analytics | email: w.vanhage@esciencecenter.nl<mailto:w.vanhage@esciencecenter.nl> |
| Netherlands eScience Center | Science Park 140 | 1098 XG Amsterdam | The Netherlands |
| The Netherlands eScience Center is a joint initiative by SURF and NWO | www.nlesc.nl<http://www.nlesc.nl/> |

On 06 Apr 2016, at 16:45, Joris Borgdorff <notifications@github.com<mailto:notifications@github.com>> wrote:


People can create stubs or remove links for the time being. I'd prefer to keep in the checks, so people don't leave until they have everything filled in. @wrvhage<https://github.com/wrvhage> agree?

**Comment by blootsvoets** [comment]
Ok, checked again, it now only tries to resolve local files if the `--local` flag is given. I'll remove that requirement.

**Comment by egpbos** [comment]
Ah, I was also updating README in a separate branch, please delete (https://github.com/NLeSC/software.esciencecenter.nl/tree/readme_7april).
