### ISSUE TITLE
contactPersonOf in person schema for project or software

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/software.esciencecenter.nl#49]
The description in of the contactPersonOf property in the person schema, says it should be a project URI, see https://github.com/NLeSC/software.esciencecenter.nl/blob/gh-pages/schema/person#L81

Like project, software also has a contactPerson property.

Can the contactPersonOf be an array of both project and software URIs?

**Comment by blootsvoets** [comment]
Yup.

**Comment by blootsvoets** [comment]
Done.
