### ISSUE TITLE
Preview website locally using docker.

### ISSUE THREAD

**Issue by arnikz** [NLeSC/software.esciencecenter.nl#79]
I've followed the instructions in README but no success yet. Here is my server log:

```
$ docker run --rm --volume=$(pwd):/srv/jekyll -i -t  -p 127.0.0.1:80:80 jekyll/jekyll:pages
Github does not allow user dependencies.
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
      Generating... 
                    done.
 Auto-regeneration: enabled for '/srv/jekyll'
Configuration file: /srv/jekyll/_config.yml
    Server address: http://0.0.0.0:4000/
  Server running... press ctrl-c to stop.
```
and I tried both localhost and 127.0.0.1 in the browser.

**Comment by sverhoeven** [comment]
What is the error in the web browser?
`Connection refused` or `Unable to connect` or `404 Not Found` or something else?

**Comment by blootsvoets** [comment]
Are you using boot2docker or docker-machine? If so, you need the IP address of the docker vm (E.g. `docker-machine ip`)

**Comment by arnikz** [comment]
Yeah, it works fine on my Linux box with Mint 17.

**Comment by blootsvoets** [comment]
Is it solved then?
