### ISSUE TITLE
software stub page passes validator, but causes docker image to fail to start

### ISSUE THREAD

**Issue by nielsdrost** [NLeSC/software.esciencecenter.nl#80]
If I create a "stub" software entry in a file called _software/amuse.md

```
---
name: AMUSE
---
```
This causes the following error:

```
Liquid Exception: undefined method `encoding' for nil:NilClass in _layouts/software.html
...error:
             Error: undefined method `encoding' for nil:NilClass
             Error: Run jekyll build --trace for more information.
````

However, the validator is just fine with my files.

Is there an example of a "minimal" software entry?

**Comment by nielsdrost** [comment]
software schema seems to imply only a name is enough:

```
     "required": ["name"],
```

**Comment by sverhoeven** [comment]
Template has been adjusted, so it can handle a document with only a name.
