### ISSUE TITLE
Migration of project descriptions from NLeSC web-page

### ISSUE THREAD

**Issue by romulogoncalves** [NLeSC/software.esciencecenter.nl#85]
Hi, 

Currently we have nice descriptions for projects already up and running or even the ones which are over. Would not be nice to clone such info into this repository, or find a way to link it to avoid redundant data? Otherwise, it is a lot of work to re-create them and it will be a lot of duplicated information.

**Comment by wrvhage** [comment]
The eStep website is meant for technical people, the corporate site for non-technical.
